create table if not exists prediction_history (
    id integer generated by default as identity primary key,
    pregnancies integer not null,
    glucose double precision not null,
    blood_pressure double precision not null,
    skin_thickness double precision not null,
    insulin double precision not null,
    bmi double precision not null,
    diabetes_pedigree double precision not null,
    age integer not null,
    probability double precision not null,
    model_probability double precision not null,
    clinical_probability double precision not null,
    risk_score integer not null,
    risk_band varchar(50) not null,
    certainty varchar(50) not null,
    has_diabetes varchar(80) not null,
    summary text not null,
    advice text not null,
    input_payload jsonb not null,
    prediction_payload jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_prediction_history_created_at
    on prediction_history (created_at desc);
