create table if not exists public.prediction_history (
    id bigint generated by default as identity primary key,
    pregnancies integer not null,
    glucose double precision not null,
    blood_pressure double precision not null,
    skin_thickness double precision not null,
    insulin double precision not null,
    bmi double precision not null,
    diabetes_pedigree double precision not null,
    age integer not null,
    probability double precision not null,
    has_diabetes text not null,
    advice text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists prediction_history_created_at_idx
    on public.prediction_history (created_at desc);
